apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: myapp
        image: zoroozz/blue-green:v1
        ports:
        - containerPort: 3000
        env:
        - name: VERSION
          value: "v1 (Blue)"
