apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: myapp
        image: zoroozz/myapp:v2
        ports:
        - containerPort: 3000
        env:
        - name: VERSION
          value: "v2 (Green)"
