apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    version: blue   # We will patch this in Jenkins later
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
